# Generated by Django 5.0.3 on 2024-04-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_json', models.CharField(default='', max_length=1000)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=300)),
                ('phone', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=1000)),
                ('zip_code', models.CharField(default='', max_length=1000)),
                ('state', models.CharField(default='', max_length=1000)),
                ('city', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
